// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCSF6Q3pzj2MVkkPcdzvToM6JNQCiIPw',
    appId: '1:1081263043947:web:08ab077a960a993f87482e',
    messagingSenderId: '1081263043947',
    projectId: 'cleanhai20092213',
    authDomain: 'cleanhai20092213.firebaseapp.com',
    storageBucket: 'cleanhai20092213.firebasestorage.app',
    measurementId: 'G-L0F5DKWP5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAruUGGSmCFvNGNoaaHXdngDS1vjVz-E',
    appId: '1:1081263043947:android:56e568c9f871090287482e',
    messagingSenderId: '1081263043947',
    projectId: 'cleanhai20092213',
    storageBucket: 'cleanhai20092213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVLIo3IGilj8ap3L5xj-cNF0b6J1cQTS0',
    appId: '1:1081263043947:ios:6c81c03fec12d74387482e',
    messagingSenderId: '1081263043947',
    projectId: 'cleanhai20092213',
    storageBucket: 'cleanhai20092213.firebasestorage.app',
    iosBundleId: 'com.example.cleanhai2',
  );
}
